export const MANDATORY_COMPONENT_OVERRIDES: {
  [key: string]: boolean;
} = {
  Html: true,
};

export const COMPONENT_OVERRIDES: {
  [key: string]: boolean;
} = {
  AmpState: true,
  Script: true,
};

export const BLACKLIST: {
  [key: string]: boolean;
} = {
  '!DOCTYPE': true,
  $REFERENCE_POINT: true,
  'O:P': true,
  'I-AMPHTML-SIZER': true,
};

export const DUPES_BLACKLIST: {
  [key: string]: boolean;
} = {
  HTML: true,
};

export const MISSING_SCRIPT_EXTENSIONS = [
  'amp-video',
  'amp-ad',
  'amp-ad-custom',
];

// The following were all copied from the global JSX IntrinsicElements
// interface.
// The properties of the interface were copied here and then had a regex replace
// run over all of them to make them into actual properties:
//
// Find: ^"?([a-z].*?)"?:.*;
//
// Replace:   $1: true,

export const JSX_INTRINSICS: {
  [key: string]: boolean;
} = {
  // HTML
  a: true,
  abbr: true,
  address: true,
  area: true,
  article: true,
  aside: true,
  audio: true,
  b: true,
  base: true,
  bdi: true,
  bdo: true,
  big: true,
  blockquote: true,
  body: true,
  br: true,
  button: true,
  canvas: true,
  caption: true,
  cite: true,
  code: true,
  col: true,
  colgroup: true,
  data: true,
  datalist: true,
  dd: true,
  del: true,
  details: true,
  dfn: true,
  dialog: true,
  div: true,
  dl: true,
  dt: true,
  em: true,
  embed: true,
  fieldset: true,
  figcaption: true,
  figure: true,
  footer: true,
  form: true,
  h1: true,
  h2: true,
  h3: true,
  h4: true,
  h5: true,
  h6: true,
  head: true,
  header: true,
  hgroup: true,
  hr: true,
  html: true,
  i: true,
  iframe: true,
  img: true,
  input: true,
  ins: true,
  kbd: true,
  keygen: true,
  label: true,
  legend: true,
  li: true,
  link: true,
  main: true,
  map: true,
  mark: true,
  menu: true,
  menuitem: true,
  meta: true,
  meter: true,
  nav: true,
  noindex: true,
  noscript: true,
  object: true,
  ol: true,
  optgroup: true,
  option: true,
  output: true,
  p: true,
  param: true,
  picture: true,
  pre: true,
  progress: true,
  q: true,
  rp: true,
  rt: true,
  ruby: true,
  s: true,
  samp: true,
  script: true,
  section: true,
  select: true,
  small: true,
  source: true,
  span: true,
  strong: true,
  style: true,
  sub: true,
  summary: true,
  sup: true,
  table: true,
  template: true,
  tbody: true,
  td: true,
  textarea: true,
  tfoot: true,
  th: true,
  thead: true,
  time: true,
  title: true,
  tr: true,
  track: true,
  u: true,
  ul: true,
  var: true,
  video: true,
  wbr: true,
  webview: true,

  // SVG
  svg: true,

  animate: true, // TODO: It is SVGAnimateElement but is not in TypeScript's lib.dom.d.ts for now.
  animateMotion: true,
  animateTransform: true, // TODO: It is SVGAnimateTransformElement but is not in TypeScript's lib.dom.d.ts for now.
  circle: true,
  clipPath: true,
  defs: true,
  desc: true,
  ellipse: true,
  feBlend: true,
  feColorMatrix: true,
  feComponentTransfer: true,
  feComposite: true,
  feConvolveMatrix: true,
  feDiffuseLighting: true,
  feDisplacementMap: true,
  feDistantLight: true,
  feDropShadow: true,
  feFlood: true,
  feFuncA: true,
  feFuncB: true,
  feFuncG: true,
  feFuncR: true,
  feGaussianBlur: true,
  feImage: true,
  feMerge: true,
  feMergeNode: true,
  feMorphology: true,
  feOffset: true,
  fePointLight: true,
  feSpecularLighting: true,
  feSpotLight: true,
  feTile: true,
  feTurbulence: true,
  filter: true,
  foreignObject: true,
  g: true,
  image: true,
  line: true,
  linearGradient: true,
  marker: true,
  mask: true,
  metadata: true,
  mpath: true,
  path: true,
  pattern: true,
  polygon: true,
  polyline: true,
  radialGradient: true,
  rect: true,
  stop: true,
  switch: true,
  symbol: true,
  text: true,
  textPath: true,
  tspan: true,
  use: true,
  view: true,
};
